### ISSUE TITLE
SyntaxError: invalid syntax in python3

### ISSUE THREAD

**Issue by csgerg** [omrivolk/pySphericalPolygon#1]
https://github.com/omrivolk/pySphericalPolygon/blob/07827b7c29849b85d2248bff08e2a1fc0909fd2e/pySphericalPolygon/__init__.py#L231

Error message:
`>>> import pySphericalPolygon as pysp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pySphericalPolygon/__init__.py", line 231
    print e
          ^
SyntaxError: invalid syntax
`
fix:
`print(e)`

**Comment by omrivolk** [comment]
Fixed it.

**Comment by csgerg** [comment]
Thanks:)
