### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by csgerg** [omrivolk/pySphericalPolygon#2]
https://github.com/omrivolk/pySphericalPolygon/blob/d964a865e363be467096196405524b37ba41829f/pySphericalPolygon/__init__.py#L313

`raise ValueError('''This polygon is too big for gnomic projection. This library can only handle polygons which can **be viewed** on a single **hemisphere**.''')`
or more verbose:
`raise ValueError('''This polygon is too big for gnomic projection (%s>%s). This library can only handle polygons which can be viewed on a single hemisphere.''' % (d_angle, np.pi/2.))`

**Comment by omrivolk** [comment]
Done. Thanks.
