### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2369: illegal multibyte sequence

### ISSUE THREAD

**Issue by lcx366** [omrivolk/pySphericalPolygon#3]
when installing pySphericalPolgon with `pip install pySphericalPolygon`, it shows the following error
```
File ".\setup.py", line 6, in <module>
    long_description=open('README.rst').read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2369: illegal multibyte sequence
```
I think the solution is replacing  `long_description=open('README.rst').read()` with ` long_description=open('README.rst','rb').read('utf-8')`. Can you update the setup.py in github and pipy?

**Comment by omrivolk** [comment]
I tried it but it doesn't work
`python setup.py sdist`

> Traceback (most recent call last):
>   File "setup.py", line 6, in <module>
>     long_description=open('README.rst','rb').read('utf-8'),
> TypeError: an integer is required

**Comment by lcx366** [comment]
I feel apologetic about my typo. It should be `long_description=open('README.rst','rb').read().decode('utf-8')`. Can you try again? thank you very much.

Another problem is that `print e` in pipy is not consistent with `print(e)` in github. For py3.x, an error will occur in `print e`.
